version: "3.5"
services: 
    jacket:
      image: "linuxserver/jackett:latest"
      ports:
        - 9117 : 9117
      volumes: 
        - local_jacket:/config
    sonarr:
      image: "linuxserver/sonarr:latest"
      ports:
        - 8989 : 8989
      volumes: 
        - sonarr_local:/config
        - /var/lib/docker/volumes/nfs_nas/_data:/mnt
      environment: 
        "SONARR_BRANCH": "main"
    radarr:
      image: "linuxserver/radarr:latest"
      ports:
        - 7878 : 7878
      volumes: 
        - radarr_local:/config
        - /var/lib/docker/volumes/nfs_nas/_data:/mnt/nas
volumes: 
  local_jacket:
    external: true
  sonarr_local:
    external: true
  radarr_local:
    external: true